import {getTranslations} from '@/lib/i18n/server';
import type { FinanceSummary } from '@/lib/finance/types';
import { formatRupiah, safeSum } from '@/lib/finance/money';
import { getMonthRange } from '@/lib/finance/dates';
export async function ChartsView({ summary,month }: { summary:FinanceSummary; month:string }) {
  const {t}=await getTranslations();
  const end = new Date(`${getMonthRange(month).endExclusive}T00:00:00Z`); end.setUTCDate(0);
  const days = Array.from({ length:end.getUTCDate() },(_,i)=>({ date:`${month}-${String(i+1).padStart(2,'0')}`,income:0,expenses:0,...summary.days.find(d=>Number(d.date.slice(-2))===i+1) }));
  const maximum = Math.max(1,...days.flatMap(d=>[d.income,d.expenses]));
  const totalExpenses = safeSum(summary.categories.map(c=>c.amount));
  return <div className="charts-layout"><section className="panel"><div className="section-heading"><h2>{t('The daily picture')}</h2><span className="muted">{t("Income & expenses")}</span></div><div className="bar-chart" role="img" aria-label={t('Daily cash flow: income {income}, expenses {expenses}. Detailed daily values follow.',{income:formatRupiah(summary.income),expenses:formatRupiah(summary.expenses)})}>{days.map((d,i)=><div className="bar-column" key={d.date}><div className="bar-pair"><span className="bar income-bar" style={{ height:`${d.income/maximum*100}%` }} title={`${d.date}: ${t('income')} ${formatRupiah(d.income)}`}/><span className="bar expense-bar" style={{ height:`${d.expenses/maximum*100}%` }} title={`${d.date}: ${t('Expenses').toLocaleLowerCase()} ${formatRupiah(d.expenses)}`}/></div><small>{i===0 || (i+1)%5===0 || i===days.length-1 ? i+1 : ''}</small></div>)}</div><div className="calendar-legend"><span><i className="summary-dot income-dot"/>{t("Income")}</span><span><i className="summary-dot expense-dot"/>{t("Expenses")}</span></div>{!summary.income && !summary.expenses && <p className="empty-inline">{t("No cash flow this month. Add an income or expense to start your chart.")}</p>}<details className="chart-details"><summary>{t("View daily amounts")}</summary><table><caption className="sr-only">{t("Daily cash flow")}</caption><thead><tr><th>{t("Date")}</th><th>{t("Income")}</th><th>{t("Expenses")}</th></tr></thead><tbody>{summary.days.filter(d=>d.income || d.expenses).map(d=><tr key={d.date}><td>{d.date}</td><td>{formatRupiah(d.income)}</td><td>{formatRupiah(d.expenses)}</td></tr>)}</tbody></table></details></section>
    <section className="panel"><h2>{t("Where it went")}</h2><p className="muted">{t("Expenses by category")}</p>{summary.categories.length ? <div className="category-bars">{summary.categories.map(c=><div key={c.name}><div className="category-bar-label"><strong>{c.name}</strong><span>{formatRupiah(c.amount)}</span></div><progress value={c.amount} max={totalExpenses} aria-label={`${c.name}: ${formatRupiah(c.amount)}`}/><small>{Math.round(c.amount/totalExpenses*100)}{t("% of expenses")}</small></div>)}</div> : <div className="empty-state"><h3>{t("No expenses yet.")}</h3><p>{t("Your category breakdown will appear here.")}</p></div>}</section>
  </div>;
}
