import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';

test('family board allows household collaboration and prevents outside access and lost edits',async()=>{
  const db=new PGlite();
  try {
    await db.exec(`create role authenticated;create role anon;create role service_role;create schema auth;
      create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      grant usage on schema auth,public to authenticated;grant execute on function auth.uid() to authenticated;`);
    for(const file of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort()) await db.exec(await readFile(`supabase/migrations/${file}`,'utf8'));
    const owner='10000000-0000-4000-8000-000000000001',member='10000000-0000-4000-8000-000000000002',outsider='10000000-0000-4000-8000-000000000003';
    await db.query(`insert into auth.users(id,email,email_confirmed_at) values($1,'owner@board.test',now()),($2,'member@board.test',now()),($3,'outsider@board.test',now())`,[owner,member,outsider]);
    const asUser=async(id:string)=>db.exec(`reset role;set request.jwt.claim.sub='${id}';set role authenticated;`);
    await asUser(owner);
    const hid=(await db.query<{id:string}>(`select create_household('Board family') as id`)).rows[0].id;
    await db.exec('reset role');
    await db.query(`insert into household_members(household_id,user_id,role) values($1,$2,'member')`,[hid,member]);
    await asUser(owner);
    const note=(await db.query<{id:string;version:number;created_by:string}>(`insert into board_items(household_id,kind,title,body,created_by) values($1,'note','School details','Bring the permission slip',$2) returning *`,[hid,outsider])).rows[0];
    assert.equal(note.created_by,owner);assert.equal(note.version,1);
    await asUser(member);
    assert.equal((await db.query(`select id from board_items where id=$1`,[note.id])).rows.length,1);
    const edit=(await db.query<{version:number;created_by:string;updated_by:string}>(`update board_items set body='Bring it on Friday',created_by=$2 where id=$1 and version=1 returning *`,[note.id,outsider])).rows[0];
    assert.equal(edit.version,2);assert.equal(edit.created_by,owner);assert.equal(edit.updated_by,member);
    assert.equal((await db.query(`update board_items set body='Old edit' where id=$1 and version=1 returning id`,[note.id])).rows.length,0);
    const one='20000000-0000-4000-8000-000000000001',two='20000000-0000-4000-8000-000000000002';
    const tasks=JSON.stringify([{id:one,text:'Rice',done:false},{id:two,text:'Milk',done:false}]);
    const todo=(await db.query<{id:string}>(`insert into board_items(household_id,kind,title,checklist) values($1,'todo','Shopping',$2) returning id`,[hid,tasks])).rows[0].id;
    await db.query(`select set_board_task($1,$2,true)`,[todo,one]);
    await asUser(owner);await db.query(`select set_board_task($1,$2,true)`,[todo,two]);
    const completed=(await db.query<{checklist:{done:boolean}[]}>(`select checklist from board_items where id=$1`,[todo])).rows[0].checklist;
    assert(completed.every(task=>task.done));
    await assert.rejects(db.query(`insert into board_items(household_id,kind,title,checklist) values($1,'todo','Invalid',$2)`,[hid,JSON.stringify([{id:one,text:' ',done:false}])]),/checklist|check constraint/i);
    await assert.rejects(db.query(`insert into board_items(household_id,kind,title) values($1,'reminder','Missing due date')`,[hid]),/check constraint/i);
    const reminder=(await db.query<{id:string}>(`insert into board_items(household_id,kind,title,due_at) values($1,'reminder','Pay electricity','2030-01-21T09:00:00+07:00') returning id`,[hid])).rows[0].id;
    await db.query(`select set_board_reminder($1,true)`,[reminder]);
    assert((await db.query<{completed_at:string}>(`select completed_at from board_items where id=$1`,[reminder])).rows[0].completed_at);
    await asUser(outsider);await db.query(`select create_household('Other family')`);
    assert.equal((await db.query(`select id from board_items where household_id=$1`,[hid])).rows.length,0);
    assert.equal((await db.query(`update board_items set title='Hacked' where id=$1 returning id`,[note.id])).rows.length,0);
    assert.equal((await db.query(`delete from board_items where id=$1 returning id`,[note.id])).rows.length,0);
    await assert.rejects(db.query(`insert into board_items(household_id,kind,title,body) values($1,'note','Hacked','Outside')`,[hid]),/row-level security/i);
    await assert.rejects(db.query(`select set_board_task($1,$2,false)`,[todo,one]),/not available/i);
    await asUser(member);await db.query(`delete from board_items where id=$1`,[note.id]);
    assert.equal((await db.query(`select id from board_items where id=$1`,[note.id])).rows.length,0);

    await asUser(owner);
    const endpoint='https://fcm.googleapis.com/fcm/send/board-test';
    await db.query(`select subscribe_board_push($1,$2,$3,'en')`,[endpoint,'A'.repeat(87),'B'.repeat(22)]);
    await assert.rejects(db.query(`select subscribe_board_push('https://127.0.0.1/private',$1,$2,'en')`,['A'.repeat(87),'B'.repeat(22)]),/check constraint/i);
    await assert.rejects(db.query(`select claim_board_notifications()`),/permission denied/i);
    await asUser(member);
    assert.equal((await db.query(`select * from push_subscriptions`)).rows.length,0);
    assert.equal((await db.query(`delete from push_subscriptions where endpoint=$1 returning id`,[endpoint])).rows.length,0);
    const due=(await db.query<{id:string}>(`insert into board_items(household_id,kind,title,due_at) values($1,'reminder','Due reminder',now()-interval '1 minute') returning id`,[hid])).rows[0].id;
    await db.exec(`reset role;update push_subscriptions set created_at=now()-interval '2 minutes';update household_members set joined_at=now()-interval '3 minutes';set role service_role;`);
    type Job={id:string;lease_id:string;board_id:string};
    const claim=async()=>((await db.query<{jobs:Job[]}>(`select claim_board_notifications() as jobs`)).rows[0].jobs);
    const jobs=await claim();assert.equal(jobs.length,1);assert.equal(jobs[0].board_id,due);
    assert.equal((await claim()).length,0);
    await db.query(`select finish_board_notification($1,$2,true,false)`,[jobs[0].id,jobs[0].lease_id]);
    assert.equal((await claim()).length,0);
    await asUser(member);await db.query(`update board_items set title='Edited title' where id=$1`,[due]);
    await db.exec('reset role;set role service_role;');assert.equal((await claim()).length,0);
    await asUser(member);
    const cancelled=(await db.query<{id:string}>(`insert into board_items(household_id,kind,title,due_at) values($1,'reminder','Cancelled',now()-interval '1 minute') returning id`,[hid])).rows[0].id;
    await db.query(`select set_board_reminder($1,true)`,[cancelled]);
    await db.exec('reset role;set role service_role;');assert.equal((await claim()).length,0);
    await asUser(member);await db.query(`select set_board_reminder($1,false)`,[cancelled]);
    await db.exec('reset role;set role service_role;');
    const next=await claim();assert.equal(next.length,1);
    await db.query(`select finish_board_notification($1,$2,false,true)`,[next[0].id,next[0].lease_id]);
    await asUser(owner);assert.equal((await db.query(`select * from push_subscriptions`)).rows.length,0);
    await asUser(member);
    await db.query(`select subscribe_board_push($1,$2,$3,'id')`,[endpoint,'A'.repeat(87),'B'.repeat(22)]);
    await db.query(`insert into board_items(household_id,kind,title,due_at) values($1,'reminder','For removed member',now()-interval '1 minute')`,[hid]);
    await db.exec(`reset role;update push_subscriptions set created_at=now()-interval '2 minutes';`);
    await db.query(`delete from household_members where user_id=$1`,[member]);
    await db.exec('set role service_role;');assert.equal((await claim()).length,0);
    await asUser(member);
    await assert.rejects(db.query(`select subscribe_board_push($1,$2,$3,'id')`,[endpoint,'A'.repeat(87),'B'.repeat(22)]),/access denied/i);
  } finally {await db.close();}
});
