import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

test('PostgreSQL enforces household isolation, financial integrity, and invitations', async () => {
  const db = new PGlite();
  try {
    await db.exec(`create role authenticated; create role anon; create schema auth;
      create table auth.users(id uuid primary key, email text, email_confirmed_at timestamptz, raw_user_meta_data jsonb default '{}');
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      grant usage on schema auth, public to authenticated;
      grant execute on function auth.uid() to authenticated;`);
    await db.exec(await readFile('supabase/migrations/202610060001_cashlendar.sql', 'utf8'));
    const owner = '10000000-0000-4000-8000-000000000001', member = '10000000-0000-4000-8000-000000000002', outsider = '10000000-0000-4000-8000-000000000003';
    await db.exec(`insert into auth.users(id,email,email_confirmed_at) values ('${owner}','owner@example.com',now()),('${member}','member@example.com',now()),('${outsider}','outsider@example.com',now());`);
    const asUser = async (id: string) => { await db.exec(`reset role; set request.jwt.claim.sub='${id}'; set role authenticated;`); };
    await asUser(owner);
    const h = (await db.query<{ id: string }>(`select public.create_household('Our family') as id`)).rows[0].id;
    await db.query(`select create_invitation('member@example.com', $1)`, ['a'.repeat(64)]);
    await asUser(outsider);
    assert.equal((await db.query('select * from public.households')).rows.length, 0);
    await assert.rejects(db.query(`select accept_invitation($1)`, ['a'.repeat(64)]), /email/i);
    const otherHousehold = (await db.query<{id:string}>(`select create_household('Other family') as id`)).rows[0].id;
    const foreignAccount = (await db.query<{id:string}>(`insert into accounts(household_id,name,type) values($1,'Private account','cash') returning id`,[otherHousehold])).rows[0].id;
    await asUser(member);
    await db.query(`select accept_invitation($1)`, ['a'.repeat(64)]);
    await assert.rejects(db.query(`select accept_invitation($1)`, ['a'.repeat(64)]), /used|household/i);
    assert.equal((await db.query('select * from public.households')).rows.length, 1);
    await assert.rejects(db.query(`select create_invitation('outsider@example.com',$1)`, ['b'.repeat(64)]), /owner/i);
    await assert.rejects(db.query(`insert into household_members(household_id,user_id,role) values($1,$2,'owner')`, [h, outsider]));
    const cash = (await db.query<{ id: string }>(`insert into accounts(household_id,name,type,opening_balance) values($1,'Cash','cash',100000) returning id`, [h])).rows[0].id;
    const savings = (await db.query<{ id: string }>(`insert into accounts(household_id,name,type,opening_balance) values($1,'Savings','savings',0) returning id`, [h])).rows[0].id;
    const category = (await db.query<{ id: string }>(`select id from categories where kind='expense' limit 1`)).rows[0].id;
    await db.query(`insert into transactions(household_id,account_id,category_id,kind,amount,date) values($1,$2,$3,'expense',20000,'2026-01-01')`, [h, cash, category]);
    await assert.rejects(db.query(`insert into transactions(household_id,account_id,category_id,kind,amount,date) values($1,$2,$3,'expense',1,'2026-01-01')`,[h,foreignAccount,category]),/missing|foreign/i);
    await assert.rejects(db.query(`insert into accounts(household_id,name,type) values($1,'Cross-household write','cash')`,[otherHousehold]),/row.level|policy|access denied/i);
    await assert.rejects(db.query(`update household_members set role='owner' where user_id=$1`,[member]));
    await db.query(`update transactions set created_by=$1,updated_by=$1,note='Backdated edit' where household_id=$2`,[owner,h]);
    const attributed = (await db.query<{created_by:string;updated_by:string}>(`select created_by,updated_by from transactions`)).rows[0];
    assert.equal(attributed.created_by,member); assert.equal(attributed.updated_by,member);
    await db.query(`insert into transfers(household_id,source_account_id,destination_account_id,amount,date) values($1,$2,$3,30000,'2026-01-01')`, [h, cash, savings]);
    const balances = (await db.query<{ account_id: string; balance: string }>('select * from account_balances()')).rows;
    assert.equal(Number(balances.find(a => a.account_id === cash)!.balance), 50000);
    const summary = (await db.query<{ result: { expenses: string; income: string; count: number } }>(`select finance_summary('2026-01-01','2026-02-01',null,null,'','') as result`)).rows[0].result;
    assert.equal(Number(summary.expenses), 20000); assert.equal(Number(summary.income), 0); assert.equal(summary.count, 2);
    await db.query(`insert into transactions(household_id,account_id,category_id,kind,amount,date,note) select $1,$2,$3,'expense',1,'2026-01-01','Pagination entry' from generate_series(1,55)`,[h,cash,category]);
    const complete = (await db.query<{result:{count:number;expenses:string}}>(`select finance_summary('2026-01-01','2026-02-01',null,null,'','') as result`)).rows[0].result;
    assert.equal(complete.count,57); assert.equal(Number(complete.expenses),20055);
    assert.equal((await db.query(`select * from list_entries('2026-01-01','2026-02-01',null,null,'','',50,0)`)).rows.length,50);
    assert.equal((await db.query(`select * from list_entries('2026-01-01','2026-02-01',null,null,'','',50,50)`)).rows.length,7);
    assert.equal((await db.query(`select * from list_entries('2026-01-01','2026-02-01',null,null,'','Backdated edit',50,0)`)).rows.length,1);
    await assert.rejects(db.query(`insert into transfers(household_id,source_account_id,destination_account_id,amount,date) values($1,$2,$2,1,'2026-01-01')`, [h,cash]));
    await assert.rejects(db.query(`insert into transactions(household_id,account_id,category_id,kind,amount,date) values($1,$2,$3,'income',1,'2026-01-01')`, [h,cash,category]), /category/i);
    await assert.rejects(db.query(`insert into transactions(household_id,account_id,category_id,kind,amount,date) values($1,$2,$3,'expense',1,'2999-01-01')`, [h,cash,category]), /date/i);
    await db.query(`insert into savings_goals(household_id,account_id,name,target_amount) values($1,$2,'Emergency fund',1000000)`, [h,savings]);
    await assert.rejects(db.query(`update accounts set archived_at=now() where id=$1`, [savings]), /goal/i);
    await assert.rejects(db.query(`insert into savings_goals(household_id,account_id,name,target_amount) values($1,$2,'Second goal',10000)`, [h,savings]));
    await db.query(`update accounts set archived_at=now() where id=$1`, [cash]);
    await assert.rejects(db.query(`insert into transactions(household_id,account_id,category_id,kind,amount,date) values($1,$2,$3,'expense',1,'2026-01-01')`, [h,cash,category]), /archived/i);
    assert.equal((await db.query('select * from transactions')).rows.length, 56);
    await asUser(owner);
    await assert.rejects(db.query(`select remove_member($1)`, [owner]), /owner/i);
    await db.query(`select remove_member($1)`, [member]);
    await asUser(member);
    assert.equal((await db.query('select * from transactions')).rows.length, 0);
    assert.equal((await db.query('select * from accounts')).rows.length, 0);
    await asUser(owner);
    await db.query(`select create_invitation('member@example.com',$1)`, ['c'.repeat(64)]);
    await db.exec(`reset role; update invitations set expires_at=now()-interval '1 day' where token_hash='${'c'.repeat(64)}';`);
    await asUser(member);
    await assert.rejects(db.query(`select accept_invitation($1)`, ['c'.repeat(64)]), /expired/i);
    await asUser(owner);
    const revoked = (await db.query<{ id: string }>(`select create_invitation('member@example.com',$1) as id`, ['d'.repeat(64)])).rows[0].id;
    await db.query('select revoke_invitation($1)', [revoked]);
    await asUser(member);
    await assert.rejects(db.query(`select accept_invitation($1)`, ['d'.repeat(64)]), /revoked/i);
    await db.exec('reset role; set role anon;');
    await assert.rejects(db.query('select * from public.accounts'), /permission/i);
    await assert.rejects(db.query(`select create_household('Anonymous')`),/permission/i);
  } finally { await db.close(); }
});
